"""empty message

Revision ID: 7535c345e35d
Revises: 241e1976a5ab
Create Date: 2020-06-30 22:46:59.813355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7535c345e35d'
down_revision = '241e1976a5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
